---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: everse-api
  namespace: everse
  labels:
    app.kubernetes.io/part-of: everse-platform
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/everse-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: everse-worker
  namespace: everse
  labels:
    app.kubernetes.io/part-of: everse-platform
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/everse-worker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: everse-ui
  namespace: everse
  labels:
    app.kubernetes.io/part-of: everse-platform
