---
apiVersion: v1
kind: Namespace
metadata:
  name: t2s
  labels:
    app.kubernetes.io/part-of: t2s-platform
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
