---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: t2s-api
  namespace: t2s
  labels:
    app.kubernetes.io/part-of: t2s-platform
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/t2s-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: t2s-worker
  namespace: t2s
  labels:
    app.kubernetes.io/part-of: t2s-platform
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/t2s-worker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: t2s-ui
  namespace: t2s
  labels:
    app.kubernetes.io/part-of: t2s-platform
