---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: t2s-api
  namespace: t2s
  labels:
    app.kubernetes.io/part-of: t2s-platform
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: t2s-api
  namespaceSelector:
    matchNames:
      - t2s
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      relabelings:
        - targetLabel: service_group
          replacement: t2s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: t2s-worker
  namespace: t2s
  labels:
    app.kubernetes.io/part-of: t2s-platform
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: t2s-worker
  namespaceSelector:
    matchNames:
      - t2s
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      relabelings:
        - targetLabel: service_group
          replacement: t2s
