---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guardrails
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: https://github.com/T2S/k8s-ai-ml-infra
    targetRevision: main
    path: workloads/guardrails
    directory:
      exclude: "application.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: guardrails
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
