---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "0" }
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-workflows
    targetRevision: 0.42.3
    helm:
      values: |
        crds:
          install: true
        workflow:
          serviceAccount:
            create: true
            name: argo-workflow
        controller:
          metricsConfig:
            enabled: true
          serviceMonitor:
            enabled: true
        server:
          authModes:
            - sso
            - server
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
